FROM golang:1.25-alpine

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY ./services/auth-service/go.mod ./
COPY ./services/auth-service/go.sum ./
RUN go mod download

COPY ./services/auth-service ./

EXPOSE 8001

CMD ["air"]