FROM golang:1.25-alpine

WORKDIR /app

COPY ./services/auth-service/go.mod ./
COPY ./services/auth-service/go.sum ./
RUN go mod download

COPY ./services/auth-service ./

RUN go build -o main ./cmd

EXPOSE 8001

CMD ["./main"]