FROM golang:1.25-alpine

WORKDIR /app

COPY ./services/user-service/go.mod ./
COPY ./services/user-service/go.sum ./
RUN go mod download

COPY ./services/user-service ./

RUN go build -o main ./cmd

EXPOSE 8002

CMD ["./main"]