FROM golang:1.25-alpine

WORKDIR /app

COPY ./services/post-service/go.mod ./
COPY ./services/post-service/go.sum ./
RUN go mod download

COPY ./services/post-service ./

RUN go build -o main ./cmd

EXPOSE 8003

CMD ["./main"]